import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "@/app/_components/footer";
// import {ThemeProvider} from "next-themes";
import { SelectedServiceProvider } from "./_provider/ServicesProvider";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
                <link
                    href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
                    rel="stylesheet" />
            </head>
            <body className={""}>
                <SelectedServiceProvider>
                    <Navbar />
                    {children}
                    <Footer />
                </SelectedServiceProvider>
            </body>
        </html>
    );
}
